name: MiniGameWorld-Rank
main: com.worldbiomusic.minigameworldrank.MiniGameWorldRankMain
version: 1.0
author: worldbiomusic
description: minigame rank plugin of MiniGameWorld 
api-version: 1.14
depend: [MiniGameWorld]
